USE BELLEVUE;

SELECT SUBSTRING(CAST(STUDENT_ID AS VARCHAR),1,1) FROM STUDENT
UNION
SELECT SUBSTRING(CAST(STUDENT_ID AS VARCHAR),1,1) FROM STUDENT_COURSE;

SELECT REPLACE(CAST(STUDENT_ID AS VARCHAR(10)), '1', '0') AS STUDENT_ID
FROM STUDENT
UNION
SELECT REPLACE(CAST(STUDENT_ID AS VARCHAR(10)), '1', '0') AS STUDENT_ID
FROM STUDENT_COURSE;

SELECT 
    SUBSTRING(CAST(STUDENT_ID AS VARCHAR(10)), 1, 1) + '-' +
    SUBSTRING(CAST(STUDENT_ID AS VARCHAR(10)), 1, 1) AS STUDENT_ID_FORMAT
FROM STUDENT
UNION
SELECT 
    SUBSTRING(CAST(STUDENT_ID AS VARCHAR(10)), 1, 1) + '-' +
    SUBSTRING(CAST(STUDENT_ID AS VARCHAR(10)), 1, 1) AS STUDENT_ID_FORMAT
FROM STUDENT_COURSE;

SELECT 
    SUBSTRING(CAST(STUDENT_ID AS VARCHAR(10)), 1, 1) AS STUDENT_ID,
    COUNT(*) AS [Count]
FROM
(
    SELECT STUDENT_ID FROM STUDENT
    UNION ALL
    SELECT STUDENT_ID FROM STUDENT_COURSE
) AS CombinedIDs
GROUP BY SUBSTRING(CAST(STUDENT_ID AS VARCHAR(10)), 1, 1)
ORDER BY STUDENT_ID;